name = "backend"
compatibility_date = "2024-09-24"
compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMGRiMmIwNTktZTIxMi00N2ViLTk4MGItZjA1NTFlNzBlOGE5IiwidGVuYW50X2lkIjoiMWQ3ZDQxMDE0NTY3OWFhNzBlODRiMGY4ZTI5OWRlNjE0MTJmYzEzMWE2ZWYwOWMwMTRjYzg3MjQ4NzJiNzY1OSIsImludGVybmFsX3NlY3JldCI6Ijk2MTdiYjI2LWM4ZDAtNGQ1ZS04ZGY5LTEzOTY2NmEzMTIyMiJ9.xv0JxziyVeZ0n0s9xXHs9BXqQf9bczDpq_Qrwn1P634"
JWT_SECRET = "dushyantJwtSecret8979798"